release:
  runs-on: ubuntu-latest
  needs: [ubuntu-build]
  if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

  steps:
    - name: Create artifacts directory
      run: mkdir -p ./artifacts

    - name: Download Ubuntu Artifact
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-build.zip
        path: ./artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}  # Use PAT instead of default GITHUB_TOKEN
      with:
        tag_name: "release-${{ github.run_id }}"
        release_name: "Automated Release ${{ github.run_id }}"
        draft: false
        prerelease: false

    - name: Upload Ubuntu Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/ubuntu-build.zip
        asset_name: ubuntu-build.zip
        asset_content_type: application/zip
